CREATE TABLE EXAMPLES (
  ID BIGINT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  AMOUNT DECIMAL(19,2) NOT NULL DEFAULT 5.0,
  ACTIVE BOOLEAN NOT NULL DEFAULT false
);

-- Ejemplo 1
INSERT INTO EXAMPLES (ID, NAME, DESCRIPTION, AMOUNT)
VALUES (1, 'Ejemplo 1', 'Descripción del Ejemplo 1', 12.5);

-- Ejemplo 2
INSERT INTO EXAMPLES (ID, NAME, DESCRIPTION, DATE, AMOUNT, ACTIVE)
VALUES (2, 'Ejemplo 2', 'Descripción del Ejemplo 2', '2023-05-17 15:30:00', 7.8, false);

-- Ejemplo 3
INSERT INTO EXAMPLES (ID, NAME, DESCRIPTION, AMOUNT, ACTIVE)
VALUES (3, 'Ejemplo 3', 'Descripción del Ejemplo 3', 9.2, true);

-- Ejemplo 4
INSERT INTO EXAMPLES (ID, NAME, DESCRIPTION, DATE, AMOUNT, ACTIVE)
VALUES (4, 'Ejemplo 4', 'Descripción del Ejemplo 4', '2023-05-16 10:00:00', 10.5, true);

-- Ejemplo 5
INSERT INTO EXAMPLES (ID, NAME, DESCRIPTION, DATE, AMOUNT, ACTIVE)
VALUES (5, 'Ejemplo 5', 'Descripción del Ejemplo 5', '2023-05-18 08:45:00', 15.2, true);